from pathlib import Path

import pandas as pd

from src.evaluate import cumulative_returns, portfolio_return_series, realized_performance_metrics
from src.optimize import (
    naive_signal_weights,
    portfolio_construction_metrics,
    rank_based_weights,
    risk_aware_optimized_weights,
)
from src.plots import plot_cumulative_returns, plot_signal_risk_tradeoff, plot_weights
from src.simulate_data import simulate_market_data


ROOT = Path(__file__).resolve().parent
DATA_DIR = ROOT / "data"
FIGURES_DIR = ROOT / "figures"
REPORTS_DIR = ROOT / "reports"


def ensure_output_directories() -> None:
    for directory in [DATA_DIR, FIGURES_DIR, REPORTS_DIR]:
        directory.mkdir(parents=True, exist_ok=True)


def markdown_table(df: pd.DataFrame, decimals: int = 4) -> str:
    """Create a small markdown table without requiring optional dependencies."""
    formatted = df.copy()
    for column in formatted.columns:
        formatted[column] = formatted[column].map(
            lambda value: f"{value:.{decimals}f}" if isinstance(value, (int, float)) else value
        )

    headers = ["method", *formatted.columns]
    rows = [[index, *formatted.loc[index].tolist()] for index in formatted.index]
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]
    lines.extend("| " + " | ".join(map(str, row)) + " |" for row in rows)
    return "\n".join(lines)


def write_summary_report(scores: pd.Series, metrics_table: pd.DataFrame) -> None:
    top_scores_table = markdown_table(scores.sort_values(ascending=False).head(6).to_frame())
    metrics_markdown = markdown_table(metrics_table)

    report = f"""# Signal-to-Portfolio Summary Report

This report is generated by `python run_analysis.py`.

The data is synthetic. The objective is not to claim a live trading edge, but to demonstrate the mechanics of translating alpha scores into portfolio weights under risk and concentration constraints.

## Top Alpha Scores

{top_scores_table}

## Portfolio Diagnostics

{metrics_markdown}

## Interpretation

- `naive_signal` allocates capital in proportion to positive signal scores.
- `rank_based` ignores signal magnitude after ranking and equally weights the top names.
- `risk_aware` keeps the portfolio fully invested while balancing signal exposure against covariance risk and maximum position size.

The main research point is that a signal ranking alone is not an implementable portfolio. It needs sizing logic, constraints, and diagnostics before it becomes a decision-ready allocation.
"""
    (REPORTS_DIR / "portfolio_summary.md").write_text(report, encoding="utf-8")


def main() -> None:
    ensure_output_directories()

    returns, scores, covariance = simulate_market_data()

    weights = {
        "naive_signal": naive_signal_weights(scores),
        "rank_based": rank_based_weights(scores, top_n=5),
        "risk_aware": risk_aware_optimized_weights(
            scores=scores,
            covariance=covariance,
            risk_aversion=20.0,
            max_weight=0.25,
        ),
    }

    weight_table = pd.concat(weights.values(), axis=1)

    metrics_table = pd.DataFrame(
        {
            name: {
                **portfolio_construction_metrics(w, scores, covariance),
                **realized_performance_metrics(returns, w),
            }
            for name, w in weights.items()
        }
    ).T

    portfolio_return_table = pd.concat(
        [portfolio_return_series(returns, w).rename(name) for name, w in weights.items()], axis=1
    )
    cumulative_return_table = portfolio_return_table.apply(cumulative_returns)

    print("\nAlpha scores:")
    print(scores.sort_values(ascending=False).round(3))

    print("\nPortfolio weights:")
    print(weight_table.round(3))

    print("\nPortfolio diagnostics:")
    print(metrics_table.round(4))

    plot_weights(weight_table, FIGURES_DIR / "portfolio_weights.png")
    plot_cumulative_returns(cumulative_return_table, FIGURES_DIR / "cumulative_returns.png")
    plot_signal_risk_tradeoff(metrics_table, FIGURES_DIR / "portfolio_diagnostics.png")

    scores.to_csv(DATA_DIR / "alpha_scores.csv")
    returns.to_csv(DATA_DIR / "simulated_returns.csv", index=False)
    weight_table.to_csv(DATA_DIR / "portfolio_weights.csv")
    metrics_table.to_csv(DATA_DIR / "portfolio_metrics.csv")
    cumulative_return_table.to_csv(DATA_DIR / "cumulative_returns.csv", index=False)

    write_summary_report(scores, metrics_table)


if __name__ == "__main__":
    main()
